### ISSUE TITLE
Add Login to Pico

### ISSUE THREAD

**Issue by windley** [Picolab/RetiredManifold#1]

**Comment by eisbaerBorealis** [comment]
Authorize through Kynetx and get root Pico ECI.

**Comment by eisbaerBorealis** [comment]
Current progress:
Replacing jqueryMobile ajax call with Angular http.

**Comment by burdettadam** [comment]
Authorization is being developed in a simple app first, and will be imported to main project after proven functionality.  
Authorize through Kynetx is working. storing token in session storage is implemented. Redirect is still being tested but looks like its working with expiration date commented out.  
Need to do:
- do we need or want expiration of oauth tokens-- no, maybe in the future...... 
- getter for token, currently the token is stored as a json string with some other variables. we need a clean getter function.

**Comment by burdettadam** [comment]
This needs testing, but seems to be working.  https://picolab.github.io/manifold/ .
manifoldAuth.authenticatedSession() in the java console should return true after log in. manifoldAuth.defaultEci should not be null.
