### ISSUE TITLE
Finalize Logo

### ISSUE THREAD

**Issue by eisbaerBorealis** [Picolab/RetiredManifold#10]
Meet with John and have him make the final adjustments to the logo.
Double-check that the team likes the logo.
Use the logo on the website.

**Comment by burdettadam** [comment]
Status:
-Logo is finalized and needs to be put into the website. 
-Logo may need to be made transparent, use ai file to do that.

**Comment by cgrimm013** [comment]
Status:
-Using prebuild changes from Jesse, the logo now scales properly in the top left of the manifold screen
