### ISSUE TITLE
Display and Add stuff to Communities

### ISSUE THREAD

**Issue by AngelSassin** [Picolab/RetiredManifold#13]
"Hack the source", get the Manifold website to display things and collections, and allow dragging and dropping things and collections into and out of other collections.

**Comment by burdettadam** [comment]
the current changes have been made to the pre-build app, we need to migrate those changes to the main app.

**Comment by AngelSassin** [comment]
What's left for this issue: 
When Communities exist, We should be able to do the following:
 1. Add a Thing to Community
     - Via tab on contained Thing card (Thing > Add to... > [Community name])
     - Via tab on containing Community card, maybe (Community > Add... > [Thing name])
     - Via drag & drop onto a Community
          - How would this be manageable if Things and Communities are on different pages?
 2. Add a Community to Community
     - Via tab on the contained Community card (Community > Add To... > [Community name])
     - Like for adding Things, via tab on the containing card (Community > Add... > [Community name])
     - Via drag & drop onto a Community. This is a big one.
 3. Remove a Thing from a Community
     - Via some clickable tab or button
     - Via drag & drop out of a Community
4. Remove a Community from a Community
     - Via some clickable tab or button
     - Via drag & drop out of a Community

**Comment by cgrimm013** [comment]
Migrated to Manifold github issues. Closing.
