### ISSUE TITLE
redirect to home page or about page if not authorized.

### ISSUE THREAD

**Issue by burdettadam** [Picolab/RetiredManifold#20]
this should be done in app/scripts/core/app.js around line 50.
commented out code attempts to redirect to login page.

**Comment by 0joshuaolson1** [comment]
Reopening because logged-in users are redirected too.

**Comment by burdettadam** [comment]
on page refresh the authorization check will fail, but after the page is loaded it will succeed.

**Comment by 0joshuaolson1** [comment]
Yay
