### ISSUE TITLE
Timed updates for separate apps?

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/RetiredManifold#33]
To increase performance, the list of "thing" objects displaying on the "thing" page caches the information in sessionStorage. As long as we keep track of any changes that are made while on that web page, we can know when to do a hard refresh by retrieving the information again from the server. What happens when the person has multiple apps up? Since sessionStorage survives a browser refresh, the app will not know if information has been changed on the pico via another app. Perhaps we could introduce a hard refresh button that the user could click, migrate the storage elsewhere, or perhaps even override the browser refresh to make certain function calls. I also wonder if there is a way for the pico to send out a notification to all apps currently "connected" to it somehow and be able to refresh that way.

**Comment by 0joshuaolson1** [comment]
Maybe Angular can distinguish between a loaded page and a reloaded one?

**Comment by cgrimm013** [comment]
Good idea. As you mentioned, somehow Github knows when a change on another tab has been made and knows that it should update something. I wonder if we could utilize that function.

**Comment by 0joshuaolson1** [comment]
It's also possible it periodically checks cookies or pings GitHub's servers. I dunno.

**Comment by cgrimm013** [comment]
Closing. As of right now, we are not concerned with multiple tabs etc opened for Manifold. If and when we get there, this issue will be created and resolved.
