### ISSUE TITLE
Feature to change an already existing Thing's name

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/RetiredManifold#41]
It seems very annoying to require someone to create an entirely new pico with the same settings and then delete the old one just to be able to change its name. See "Panels" page under Features on the navigation bar of Manifold; there is an example feature for the UI to do something like that.

Note: As of right now, the original pico engine does not support renaming picos...

**Comment by burdettadam** [comment]
closing and moving to working manifold repo.
