### ISSUE TITLE
Oauth with NPE

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/RetiredManifold#47]
Redirect not to kynetx, but to a localhost:8080 pico engine for oauth.

**Comment by windley** [comment]
Ultimately we need to let people choose this. We haven't talked about discovery, so just a place to enter it in Manifold login would be OK for now. I'm envisioning a single field form that lets you put your pico engine URL in (with http://localhost:8080 as the default) and a button that says "Link".

That would take you to the Oauth API on the engine.

**Comment by cgrimm013** [comment]
Ok. I'll make sure to add that feature along with this enhancement.

**Comment by cgrimm013** [comment]
Pushed changes to authorize with localhost:8080 NPE server. Next step: add the Link button and only default to localhost:8080 if another option is not provided.

**Comment by cgrimm013** [comment]
Link button has been added. Note: since version 0.12.6 of NPE, only the latest version of node works with authorization, not just version 4 and up as stated in the docs. This problem is being researched.
