### ISSUE TITLE
Manifold.js API

### ISSUE THREAD

**Issue by burdettadam** [Picolab/RetiredManifold#6]
we need javascript that structures the api for the website to use. this javascript will be a wrapper for events and queries.

**Comment by burdettadam** [comment]
look at https://github.com/kynetx/Fuse-API/blob/master/js/fuse-api.js as an example. also look at https://github.com/Picolab/devtools/blob/gh-pages/js/devtools-api.js as an example.

**Comment by cgrimm013** [comment]
The file itself is created and pushed to Github with the controllers (the same place as the wranglerSDK file). As of right now, it is mostly a skeleton with only one or two actually constructed/working functions. We need to add more files as we see fit.

**Comment by cgrimm013** [comment]
Rewrite this for ReactJS and add to the Manifold rewrite project.

**Comment by burdettadam** [comment]
cgrimm013 has rewritten wrangler sdk to export all function to be better used in react and javascript generally. Moving issue to working Manidfold repo.
