### ISSUE TITLE
General Manifold ruleset (spime)

### ISSUE THREAD

**Issue by burdettadam** [Picolab/RetiredManifold#7]
This ruleset should have all the general things needed for manifold things to work.
review https://github.com/kynetx/Fuse-API/blob/master/api/fuse_vehicle.krl for an example of a general ruleset for vehicles that belong to a fleet. Much like a spime that belongs to a manifold pico.

**Comment by burdettadam** [comment]
current work with Manifold rulesets is here https://github.com/burdettadam/Practice-with-KRL/tree/master/manifold.
only the ability so far is to create a manifold pico and get its eci.

**Comment by burdettadam** [comment]
we will have Owner, manifold, collections, things.
things will be the basic "object" functionality, like lights.
collections will have subscriptions to objects, currently a basic container. 
manifold will manage collection and things lifecycle. manifold is the parent of all things, in charge of managing everything. manifold is the app interface.

**Comment by windley** [comment]
What is the base functionality we want for the `manifold_thing` ruleset? 
- respond to life cycle events for initialization and cleanup
- picoStatus
- configuration using Wrangler
- autoSubscribe to Manifold pico
- route to Manifold
- timeline (might be companion ruleset)

**Comment by burdettadam** [comment]
look at https://github.com/Picolab/manifold/tree/gh-pages/KRL for what has been done so far. the rulesets do need to be updated with correct ruleset id's before they will work.

**Comment by burdettadam** [comment]
moved to working manifold.
